name: piefed_api_client
description: A Future-based http client for the PieFed API.
version: 0.1.0
repository: https://github.com/79623798464325/piefed_api_client


environment:
  sdk: ^3.7.0

dependencies:
  freezed_annotation: ^2.4.4
  http: ^1.3.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.8
  json_serializable: ^6.9.0
  lints: ^5.1.1
  test: ^1.25.15
